### ISSUE TITLE
docker로 guinicorn 실행하기

### ISSUE THREAD

**Issue by baebug** [baebug/Napoleon#5]
[#4]

**Comment by baebug** [comment]
settings 설정하는 부분은 #4 에 있음
Dockerfile
```
FROM python:3

# set work directory
WORKDIR /app

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# install dependencies
RUN pip install --upgrade pip
COPY ./requirements.txt /app/requirements.txt
RUN pip install -r requirements.txt

# copy project
COPY . /app/

CMD ["python", "managy.py", "collectstatic"]
CMD ["gunicorn", "--bind", "0.0.0.0:8000", "conf.wsgi:application"]

EXPOSE 8000
```

**Comment by baebug** [comment]
어차피 requirements.txt나 package.json 가져가서 dependency 다 받고 복사하니까 모폴더내에 venv랑 node_modules 두지말것
(쓸데없이 이미지만 커진다.)
아니면 dockerignore 추가 ---> 나중에 알아보기

**Comment by baebug** [comment]
`nginx`에서 다른 container routing해주는데 `depends_on`과 `expose`가 필요하다고 함.
`depends_on`은 `dockerfile`에 없고 `docker-compose.yml`에만 있는것 같아서 `docker-compose.yml`을 작성해주었다.
```
version: "3"
services:
  nginx:
    container_name: nginx
    restart: always
    build: ./test-nginx/.
    ports:
      - "80:80"
    depends_on:
      - gunicorn
  gunicorn:
    container_name: gunicorn
    restart: always
    build: ./test-django/.
    ports:
      - "8000:8000"
    expose:
      - "8000"
```

`service name`도 생겼으니 `/sites-available/django.example.local` 에 `upstream`도 넣어주었다.
```
upstream web {
    server gunicorn:8000;
}

server {
    listen       80;
    server_name  django.example.local;

    #access_log  /var/log/nginx/host.access.log  main;

    location / {
        proxy_pass      http://web;
        proxy_http_version 1.1;
    }

    #error_page  404              /404.html;

    # redirect server error pages to the static page /50x.html
    #
    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}
```

이렇게하니 `ALLOWED_HOST`에 `web`을 추가해주라고 떠서 추가해주었다.
