### ISSUE TITLE
s_fac_django / docker-compose.testprod.yml

### ISSUE THREAD

**Issue by baebug** [baebug/Napoleon#7]
db:

web:

**Comment by baebug** [comment]
Dockerfile
```
# pull official base image
FROM python:3.8.3-alpine

# set work directory
WORKDIR /code

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# install dependencies
RUN pip install --upgrade pip
COPY ./requirements/testprod.txt /code/requirements.txt
RUN apk add jpeg-dev zlib-dev
RUN \
 apk add --no-cache postgresql-libs && \
 apk add --no-cache --virtual .build-deps gcc musl-dev postgresql-dev && \
 python3 -m pip install -r requirements.txt --no-cache-dir && \
 apk --purge del .build-deps

# copy project
COPY . /code/
```

docker-compose.testprod.yml
```
version: "3.9"

services:
  db:
    container_name: sf_db
    image: postgres
#    command: sh -c "mkdir /var/lib/media"
    restart: always
    environment:
      POSTGRES_DB: s_factory
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - /home/ubuntu/services/sf/postgresql/data:/var/lib/postgresql/data
  web:
    container_name: sf_web
    build: .
    command: sh ./deploy/docker-entrypoint.sh
    volumes:
      - .:/code
      - /home/ubuntu/services/sf/media:/var/lib/media
    ports:
      - "7000:7000"
    depends_on:
      - db

```

root 디렉토리에 `services/sf/postgresql` `services/sf/media` 분리 후 data를 밖에서 관리
fixture도 빼야하는가?
